# Generated by Django 4.0 on 2021-12-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('date_ana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_auto_now', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('organizer_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='meetups.location')),
                ('participant', models.ManyToManyField(blank=True, null=True, related_name='meetups', to='meetups.Participant')),
            ],
        ),
    ]
